"""StadiumIQ FastAPI application factory.

Assembles the application with middleware, CORS, rate-limiting, and routing.
Startup checks verify Supabase connectivity and warn about rate-limit
storage in production.
"""

from __future__ import annotations

import logging
from contextlib import asynccontextmanager
from typing import TYPE_CHECKING

import httpx
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles
from slowapi import _rate_limit_exceeded_handler
from slowapi.errors import RateLimitExceeded

from app.core.config import get_settings
from app.core.logging import RequestIdMiddleware, setup_logging
from app.core.rate_limit import check_production_storage, limiter
from app.core.security import SecurityHeadersMiddleware
from app.routes.auth import auth_router
from app.routes.main import router

if TYPE_CHECKING:
    from collections.abc import AsyncIterator

logger = logging.getLogger("stadiumiq")


@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncIterator[None]:
    """Application lifespan handler — runs startup and shutdown logic.

    Startup:
    - Checks Supabase connectivity.
    - Warns if rate-limit storage is memory:// in production.

    Args:
        app: The FastAPI application instance.

    Yields:
        Control to the running application.
    """
    settings = get_settings()

    # ── Check Supabase connectivity ──────────────────────────────────────
    if settings.supabase_url:
        try:
            async with httpx.AsyncClient(timeout=5.0) as client:
                resp = await client.get(
                    f"{settings.supabase_url}/rest/v1/",
                    headers={"apikey": settings.supabase_service_role_key},
                )
            if resp.status_code in (200, 400):  # 400 = reachable but no table specified
                logger.info("Supabase is reachable at %s", settings.supabase_url)
            else:
                logger.warning(
                    "Supabase returned status %d at startup",
                    resp.status_code,
                )
        except httpx.HTTPError as exc:
            logger.warning(
                "Supabase unreachable at startup: %s — "
                "the app will run but persistence will be degraded.",
                exc,
            )
    else:
        logger.warning("SUPABASE_URL not set — history persistence is disabled.")

    # ── Rate-limit storage check ─────────────────────────────────────────
    check_production_storage()

    logger.info(
        "StadiumIQ backend started",
        extra={
            "extra_data": {
                "environment": settings.environment,
                "ai_enabled": settings.use_ai,
                "version": settings.app_version,
            }
        },
    )

    yield  # ── Application runs here ─────────────────────────────────────

    logger.info("StadiumIQ backend shutting down")


def create_app() -> FastAPI:
    """Build and configure the FastAPI application.

    Returns:
        A fully-configured FastAPI instance ready to serve.
    """
    # ── Logging first ────────────────────────────────────────────────────
    setup_logging()

    settings = get_settings()

    # ── App instance ─────────────────────────────────────────────────────
    app = FastAPI(
        title="StadiumIQ — FIFA World Cup 2026",
        description="Stadium operations intelligence platform",
        version=settings.app_version,
        docs_url="/api/docs" if settings.environment != "production" else None,
        redoc_url=None,
        lifespan=lifespan,
    )

    # ── Middleware (order matters — outermost first) ──────────────────────
    app.add_middleware(RequestIdMiddleware)
    app.add_middleware(SecurityHeadersMiddleware)
    app.add_middleware(
        CORSMiddleware,
        allow_origins=settings.get_allowed_origins(),
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    # ── Rate limiting ────────────────────────────────────────────────────
    app.state.limiter = limiter
    app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)  # type: ignore[arg-type]

    # ── Routes ───────────────────────────────────────────────────────────
    app.include_router(router)
    app.include_router(auth_router)

    # ── Frontend Static Files (for Docker / Production) ──────────────────
    import os

    # Path to the built frontend (relative to /app in Docker)
    static_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "frontend", "dist")

    if os.path.exists(static_dir):  # pragma: no cover
        # Serve the /assets directory generated by Vite
        app.mount("/assets", StaticFiles(directory=os.path.join(static_dir, "assets")), name="assets")

        # Catch-all route for React Router client-side routing
        @app.get("/{full_path:path}", include_in_schema=False)
        async def serve_frontend(full_path: str) -> FileResponse:
            # Resolve the requested path and the static root to their real,
            # absolute forms so "." / ".." segments (raw or percent-encoded)
            # are collapsed. We then require the resolved path to still live
            # *inside* static_dir before serving it — otherwise os.path.join()
            # would happily walk outside the intended directory (e.g. via
            # "%2e%2e/%2e%2e/etc/passwd") and FileResponse would serve
            # arbitrary files off disk.
            static_dir_real = os.path.realpath(static_dir)
            requested_path = os.path.realpath(os.path.join(static_dir, full_path))

            is_within_static_dir = (
                requested_path == static_dir_real
                or requested_path.startswith(static_dir_real + os.sep)
            )

            if full_path and is_within_static_dir and os.path.isfile(requested_path):
                return FileResponse(requested_path)

            # For all other routes, serve index.html to let React Router handle it
            return FileResponse(os.path.join(static_dir, "index.html"))

    return app


# Module-level app instance for ``uvicorn app.main:app``
app = create_app()
