"""StadiumIQ FastAPI application factory.

Assembles the application with middleware, CORS, rate-limiting, and routing.
Startup checks verify PocketBase connectivity and warn about rate-limit
storage in production.
"""

from __future__ import annotations

import logging
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager

import httpx
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from slowapi import _rate_limit_exceeded_handler
from slowapi.errors import RateLimitExceeded

from app.core.config import get_settings
from app.core.logging import RequestIdMiddleware, setup_logging
from app.core.rate_limit import check_production_storage, limiter
from app.core.security import SecurityHeadersMiddleware
from app.routes.auth import auth_router
from app.routes.main import router

logger = logging.getLogger("stadiumiq")


@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncIterator[None]:
    """Application lifespan handler — runs startup and shutdown logic.

    Startup:
    - Checks PocketBase connectivity.
    - Warns if rate-limit storage is memory:// in production.

    Args:
        app: The FastAPI application instance.

    Yields:
        Control to the running application.
    """
    settings = get_settings()

    # ── Check PocketBase ─────────────────────────────────────────────────
    try:
        async with httpx.AsyncClient(timeout=5.0) as client:
            resp = await client.get(f"{settings.pocketbase_url}/api/health")
        if resp.status_code == 200:
            logger.info("PocketBase is reachable at %s", settings.pocketbase_url)
        else:
            logger.warning(
                "PocketBase returned status %d at startup",
                resp.status_code,
            )
    except httpx.HTTPError as exc:
        logger.warning(
            "PocketBase unreachable at startup: %s — "
            "the app will run but auth and persistence will fail.",
            exc,
        )

    # ── Rate-limit storage check ─────────────────────────────────────────
    check_production_storage()

    logger.info(
        "StadiumIQ backend started",
        extra={
            "extra_data": {
                "environment": settings.environment,
                "ai_enabled": settings.use_ai,
                "version": settings.app_version,
            }
        },
    )

    yield  # ── Application runs here ─────────────────────────────────────

    logger.info("StadiumIQ backend shutting down")


def create_app() -> FastAPI:
    """Build and configure the FastAPI application.

    Returns:
        A fully-configured FastAPI instance ready to serve.
    """
    # ── Logging first ────────────────────────────────────────────────────
    setup_logging()

    settings = get_settings()

    # ── App instance ─────────────────────────────────────────────────────
    app = FastAPI(
        title="StadiumIQ — FIFA World Cup 2026",
        description="Stadium operations intelligence platform",
        version=settings.app_version,
        docs_url="/api/docs" if settings.environment != "production" else None,
        redoc_url=None,
        lifespan=lifespan,
    )

    # ── Middleware (order matters — outermost first) ──────────────────────
    app.add_middleware(RequestIdMiddleware)
    app.add_middleware(SecurityHeadersMiddleware)
    app.add_middleware(
        CORSMiddleware,
        allow_origins=["http://localhost:5173", "http://localhost:3000"],
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    # ── Rate limiting ────────────────────────────────────────────────────
    app.state.limiter = limiter
    app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)  # type: ignore[arg-type]

    # ── Routes ───────────────────────────────────────────────────────────
    app.include_router(router)
    app.include_router(auth_router)

    # ── Frontend Static Files (for Docker / Production) ──────────────────
    import os
    from fastapi.staticfiles import StaticFiles
    from fastapi.responses import FileResponse
    
    # Path to the built frontend (relative to /app in Docker)
    static_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "frontend", "dist")
    
    if os.path.exists(static_dir):
        # Serve the /assets directory generated by Vite
        app.mount("/assets", StaticFiles(directory=os.path.join(static_dir, "assets")), name="assets")
        
        # Catch-all route for React Router client-side routing
        @app.get("/{full_path:path}", include_in_schema=False)
        async def serve_frontend(full_path: str):
            # Check if it's a specific file request (like favicon.ico, etc.)
            file_path = os.path.join(static_dir, full_path)
            if full_path and os.path.isfile(file_path):
                return FileResponse(file_path)
            
            # For all other routes, serve index.html to let React Router handle it
            return FileResponse(os.path.join(static_dir, "index.html"))

    return app


# Module-level app instance for ``uvicorn app.main:app``
app = create_app()
